### ISSUE TITLE
在neovide 首次输入中卡顿

### ISSUE THREAD

**Issue by MOldtime** [rime/weasel#991]
**上报前请检查**
- [x] 我遇到的问题没有其他人在 issue 里提到过
- [x] 我的小狼毫版本于 rime/weasel 下载
- [x] 我在使用小狼毫的最新发布版本，或最新发布版本后的 CI 构建

**操作系统信息**
 - OS 详细版本: `Windows 11 23H2 25931.1010`
 - 小狼毫版本: 803fcfc

**描述遇到的问题**
在[neovide](https://github.com/neovide/neovide)中输入中文
首次输入都会卡顿1s

**复现步骤**
重现问题的步骤，如：
1. 打开Neovide
2. 在其中输入中文

**预期行为**
首次输入中文不卡顿

**用户文件**
请于此附上 weasel 用户文件夹下的内容，方便开发者调试问题
[Rime.zip](https://github.com/rime/weasel/files/12476711/Rime.zip)

**截图**
如果问题需要，可附上 GIF 图片
可以在左下角看到我按键按下的时间，当我切换到中文后，首次输入会等待一会才显示候选

https://github.com/rime/weasel/assets/38435967/f7c179fc-8b11-4c05-9a0c-14e47fc2e816

**其他补充说明**
其实我也怀疑是`neovide`的问题，并提了问题
不过在我测试下，微软的输入法在neovide中没有这个问题
所以我又不得不认为是weasel的问题

**Comment by MOldtime** [comment]
> 未复现问题，803fcfc，Windows 10 64bit，neovide [0.11.1](https://github.com/neovide/neovide/releases/tag/0.11.1)

@fxliang  我应该提供更多的资料 我重新编辑了问题 上传了用户文件夹与视频演示，可能这本身就是Windows11 的问题

**Comment by fxliang** [comment]
Windows10下，依然无法复现问题，这个只能再看了。

**Comment by fredizzimo** [comment]
Sorry for typing in English, but I think it's better that you translate it on your end if needed.

I was wondering if the issue could be the virus scanner scanning the process before allowing it to be run? It's not very likely, since it seems to be a Neovide specific issue at least as reported here https://github.com/neovide/neovide/issues/1989.

@MOldtime, you could try one thing, to see if Neovide itself is responsive, if you run `neovide --noidle`, and then inside Neovide `:let g:neovide_profiler=1`. You should see the graph constantly updating, if that freezes, we know that Neovide itself freezes as well.

Another unlikely cause could be the Windows event queue filling up. That should be fixed in https://github.com/neovide/neovide/pull/1977, so it would be great if you are able to test with that as well. You will need Neovim 0.9.2.

**Comment by MOldtime** [comment]
@fredizzimo Thanks Reply
> I was wondering if the issue could be the virus scanner scanning the process before allowing it to be run? It's not very likely, since it seems to be a Neovide specific issue at least as reported here https://github.com/neovide/neovide/issues/1989.

I have turned off the anti-virus application
----
> you could try one thing, to see if Neovide itself is responsive, if you run neovide --noidle, and then inside Neovide :let g:neovide_profiler=1. You should see the graph constantly updating, if that freezes, we know that Neovide itself freezes as well.

https://github.com/rime/weasel/assets/38435967/cffba930-3d4a-4700-87c4-3a4612e1c639

----
> Another unlikely cause could be the Windows event queue filling up. That should be fixed in https://github.com/neovide/neovide/pull/1977, so it would be great if you are able to test with that as well. You will need Neovim 0.9.2.

I can't test it because he can't switch to Chinese, which is weird

**Comment by fredizzimo** [comment]
@MOldtime, it looks like Neovide freezes for a second or so when you use `--noidle`, but there's a long delay before that too. Without `--noidle` it's hard to tell, since the graph does not update unless something new happens.

> I can't test it because he can't switch to Chinese, which is weird.

That's very weird indeed. I don't think I have done any changes that should stop IME from working there. I even made a work in progress branch based on a little bit older versions https://github.com/fredizzimo/neovide/tree/fsundvik/ime, to allow IME pre-edit. so that you can see what you type directly in the editor area, and it was working for me then. 

Maybe you somehow have IME disabled in Neovim https://neovide.dev/configuration.html#ime? But the default should be enabled.

**Comment by MOldtime** [comment]
@fredizzimo Disabled input methods have been excluded because their configuration files are shared
The test results are still the same as last night
I completely recorded the operation process. If there is any improper operation, it is convenient to point out. However, since the video file is larger than 10MB, it cannot be uploaded directly to Github, so I use other methods to share it.

[OneDrive](https://1drv.ms/v/s!AlG5xn34uMgmgg4HZI-q5bmdbdAv?e=kKnFhK)

**Comment by fredizzimo** [comment]
Ok I will try weasel myself, a little bit later. 

But the exe you downloaded was not actually from my IME branch, try this one https://github.com/fredizzimo/neovide/actions/runs/5778629981.

**Comment by MOldtime** [comment]
> Ok I will try weasel myself, a little bit later.
> 
> But the exe you downloaded was not actually from my IME branch, try this one https://github.com/fredizzimo/neovide/actions/runs/5778629981.

@fredizzimo After correction, the problem still exists
Maybe this is a problem with Windows 11 itself

https://github.com/rime/weasel/assets/38435967/a4ea1749-3c48-4f69-ae7c-ce36e11b1f5c

**Comment by fredizzimo** [comment]
I have windows 11, so let’s see what happens when I try it later.

**Comment by fredizzimo** [comment]
I have not debugged further, but here are two observations that I made.

1. I have the same problem; I can't activate the IME mode after Neovide launches. But I found a workaround, just switch away from Neovide, open the start menu for example, and then go back, and it will start working. I don't see any delays, like the earlier reports.
2. The popup menu where you type is in the wrong location after that, it's in the lower right corner of the screen, not even inside the Neovide window.

But then I tried the built-in windows IME, and that behaves the same way for Chinese. The Korean one worked, but that one works differently, and is more like typing normally. So, there's something that we are doing wrong in the rendering branch on Windows. I think I was using Linux when I was doing the pre-edit stuff and did not notice, everything worked perfectly there.

With Neovide 0.11.2, I see maybe a small delay, but a very short one. The position is wrong for the first input, but the rest are correct, so it's not fully working.

I will look more into this later, but right now I don't know what's wrong, and if the problem is in Neovide or the winit library that we are using. If someone has any ideas of what could be wrong, then please tell me, that will save a lot of debugging.

**Comment by fxliang** [comment]
in early version of Neovide, when we type with weasel and select candidate by <space>,  there would be double insertion, but no problem when select candidate by clicking mouse. 

then with the latest version of Neovide, that problem just not happened, I am not sure about what were changed inside.
some days before we doubted about the TSF process in weasel not right, however we found nothing obviously wrong.

maybe there are mistakes in both weasel and Neovide.

**Comment by MOldtime** [comment]
@fredizzimo Thank you very much for researching this issue
After I used the latest ci build he problem was basically solved  60c7a71
The delay dropped from the initial 1200ms to 40ms, which should be a normal overhead.
Also a big thank you to @fxliang for the fix
